name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Standard:
    runs-on: ubuntu-latest
    name: Standard
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run Standard
      run: bin/rake standard
