name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    name: Standard
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Standard
      run: bin/rake standard

  Tests:
    runs-on: ubuntu-latest
    name: Test with ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the tests
      run: bin/rake spec
