name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  RSpec:
    runs-on: ubuntu-latest
    name: RSpec on Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
        - '3.0.0'
        - '3.1.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the tests
      run: bin/rake spec
